config/routes.rb
MakeSandwich::Application.routes.draw do

  resources :orders
  match '/404' => 'error#not_found'
  match '/422' => 'error#server_error'
  match '/500' => 'error#server_error'
  match '*path' => redirect('/')

   root :to => 'orders#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :name
  attr_accessible :sandwich
  attr_accessible :special_instructions
  #validates_column :sandwich
  validates_inclusion_of :sandwich, :in => ["Meat", "Vegetarian", "Vegan"]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/error_controller.rb
class ErrorController < ApplicationController

	def not_found
		render :status => 404, :formats => [:html]
	end

	def server_error
		render :status => 500, :formats => [:html]
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

def index
	
end

def new
	@order = Order.new
	respond_to do |format|
    format.html  # new.html.erb
    format.json  { render :json => @order }
	
	end

end

def create
	@order = Order.new(params[:order])
	 respond_to do |format|
    if @order.save
    UserMailer.sandwich_order(@order).deliver
      format.html { redirect_to(@order, :notice => 'Order has been saved!') }
      format.xml  { render :xml => @order, :status => :created, :location => @order }
    else
      format.html { render :action => "new" }
      format.xml  { render :xml => @order.errors, :status => :unprocessable_entity }
    end
  end

end


def show
	@order = Order.find(params[:id])
	respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end

end

def edit
	@order = Order.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <title>MakeSandwich</title>
  <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
  <!-- <link href='http://twitter.github.com/bootstrap/assets/css/docs.css' rel='stylesheet'> -->
  
</head>
<body>
	
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
<style>

div {
	text-align: center;
	font-family:"Georgia", Georgia, serif;
}


background_pic.transparent {
opacity:0;
}
.hero-unit {
	text-align: center;
	padding: 30px;
	margin-bottom: 30px;
	background-repeat: no-repeat;
	-webkit-border-radius: 6px;
	-moz-border-radius: 6px;
	border-radius: 6px;
	background-color: #1a82f7;
	background: url(images/linear_bg_2.png);
	background-repeat: repeat-x;

  	/* Safari 4-5, Chrome 1-9 */
  	background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#1a82f7), to(#2F2727));

  	/* Safari 5.1, Chrome 10+ */
  	background: -webkit-linear-gradient(top, #2F2727, #1a82f7);

  	/* Firefox 3.6+ */
  	background: -moz-linear-gradient(top, #2F2727, #1a82f7);

  	/* IE 10 */
  	background: -ms-linear-gradient(top, #2F2727, #1a82f7);

  	/* Opera 11.10+ */
  	background: -o-linear-gradient(top, #2F2727, #1a82f7);
}


</style>
    <div class="container">
         
         <div class="hero-unit">
         <h1><strong>MAKE ME A SAMMICH!</strong></h1>
         <small><em>All right, calm down. Just use this app...Jeez...</em></small>
         <p></p>
         </div><!-- .hero-unit -->

	<%= yield %>

</body>
</html>

app/views/order/new.html.erb
<h1>Please fill out your order form</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', orders_path %>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="form-horizontal">
  <div class="control-group">
    <label class="control-label" for="inputName">Name</label>
    <div class="controls">
      <input type="text" id="inputEmail" placeholder="Who are you?">
    </div>
  </div>

  <div class="field">
    <%= f.label :sandwich %><br />
    <%= f.select :sandwich, [:Meat, :Vegetarian, :Vegan] %>
    </div>

  <div class="control-group">  
    <label class="control-label" for="textarea">Special Instructions</label>  
    <div class="controls">  
    <textarea class="input-xlarge" id="textarea" rows="3"></textarea>  
    </div>  
  </div>  

  <div class="control-group">
    <div class="form-actions">
    <button class="btn btn-primary" type="submit">Order!</button>
    </div>
  </div>
</form>

<% end %>

app/views/orders/index.html.erb
<h2> Hungry?<h2>
<h2> How about we make you a sandwich? <h2>

<h2>To order one just click <%= link_to 'here', new_order_path %> <h2>

<h2> Have a wonderful day! <h2>

app/views/orders/new.html.erb
<h1>Please fill out your order form</h1>
 
<%= render 'form' %>
 

app/views/orders/show.html.erb
<link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
<h1>Thanks for the order!<h1>
	<h2>Please use our service again to get delicious (and sometimes nutritious!) sandwiches!<h2>
	<h2> Have a beautiful day! <h2>


<%= link_to 'Make New Order', orders_path %>